type NewsAction = {
  TOP_NEWS_REQUEST: string;
  TOP_NEWS_SUCCESS: string;
  TOP_NEWS_FAILURE: string;
  NEWS_DETAIL_SUCCESS: string;
  NEWS_DETAIL_FAILURE: string;
  COMMENTS_REQUEST: string;
  COMMENTS_SUCCESS: string;
  COMMENTS_FAILURE: string;
};

export const NEWS_ACTION: NewsAction = {
  TOP_NEWS_REQUEST: 'TOP_NEWS_REQUEST',
  TOP_NEWS_SUCCESS: 'TOP_NEWS_SUCCESS',
  TOP_NEWS_FAILURE: 'TOP_NEWS_FAILURE',
  NEWS_DETAIL_SUCCESS: 'NEWS_DETAIL_SUCCESS',
  NEWS_DETAIL_FAILURE: 'NEWS_DETAIL_FAILURE',
  COMMENTS_REQUEST: 'COMMENTS_REQUEST',
  COMMENTS_SUCCESS: 'COMMENTS_SUCCESS',
  COMMENTS_FAILURE: 'COMMENTS_FAILURE',
};
